### ISSUE TITLE
Incompatible with PHP 7.3

### ISSUE THREAD

**Issue by nix0x00** [olegnax/module-core#1]
hi, I am using Magento 2.3.5, and required php is 7.3. However, this extension is not compatible, could you please update the PHP requirement?

` Package olegnax/module-core at version  has a PHP requirement incompatible with your PHP version (7.3.19) `

**Comment by olegnax** [comment]
It is compatible with 7.3. If you install it manually everything will be ok, but via composer it had dependencies to 7.1 and 7.2. I've updated them so you can install it on 7.3 via composer also.
