### ISSUE TITLE
No release for module with fixed Magento 2.4.6 compatibility

### ISSUE THREAD

**Issue by vmalyk** [olegnax/module-core#2]
Hi, 
on install by Composer We got error:
 
![image](https://github.com/olegnax/module-core/assets/5318027/de9b28cb-4bc5-48a3-beab-e891a15ff81c)

As I see it's fixed and requires tag new version only:
![image (1)](https://github.com/olegnax/module-core/assets/5318027/70f954eb-3074-4de2-9ded-8d4b4e500739)

**Comment by davidwindell** [comment]
Yes please @olegnax :pray: 

(in the meantime `"olegnax/module-core": "dev-master#3641d7847c39e2ec4be39aa41b17789d355cdea4 as 1.3.5"`)

**Comment by olegnax** [comment]
Sorry guys. Added new release.

**Comment by davidwindell** [comment]
Thanks @olegnax but could you also update Packagist please?

**Comment by vmalyk** [comment]
@davidwindell , new version is available on Packagist.
